// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'todo.freezed.dart';
// optional: Since our Todo class is serializable, we must add this line.
// But if Todo was not serializable, we could skip it.
part 'todo.g.dart';

@freezed
abstract class Todo implements _$Todo {
  const Todo._();
  const factory Todo({
    required String description,
    required String id,
    required bool completed,
  }) = _Todo;

  void method() {
    print('hello world');
  }

  factory Todo.fromJson(Map<String, Object?> json)
      => _$TodoFromJson(json);
}